defaults: &defaults
  docker:
    - image: circleci/node:10.1.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Lint
          command: npm run lint
  semver:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Semantic Release
          command: node_modules/.bin/semantic-release pre && node_modules/.bin/semantic-release post
workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - lint:
          requires:
            - build
      - semver:
          requires:
            - build
            - lint
          filters:
            branches:
              only: master
    #   - publish:
    #       requires:
    #         - build
    #         - lint
    #       filters:
    #         branches:
    #           only: develop